### PR TITLE
fix(DevSupportManager): Progress dialog message corrected for debugging

### LINKED ISSUE #310: Fix up ProgressDialog message and behavior
The message is incorrect during Chrome debugging, and it does not prevent trying to show another progress dialog while a progress dialog is already active.

### PR DESCRIPTION
**Pull request by rozele**
The progress dialog for requests to the debug service was always related to "fetching the JS bundle", when sometimes the progress dialog represents waiting for connections to the Chrome debugger.

Fixes #310

### CODE REVIEW

File: ReactWindows/ReactNative/UIManager/ShadowNodeRegistry.cs [hunk 1]
```diff
@@ -33,7 +32,7 @@ public ICollection<int> RootNodeTags
         /// <param name="node">The node.</param>
         public void AddRootNode(ReactShadowNode node)
         {
-            if (node == null)
+           if (node == null)
```
Comment (rozele) [inline ReactWindows/ReactNative/UIManager/ShadowNodeRegistry.cs]: Fix this whitespace change.
